# Site settings
title: TeachCoder | Reach Each to Teach
email: arnav@teachcoder.in
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "www.teachcoder.in" # the base hostname & protocol for your site

twitter_username: "@teachcoder"
github_username:
facebook_username: "teachcoder"

# Build settings
markdown: kramdown
